version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 33700:5432
    volumes:
      - ./data/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_fastapi